(require 'weblogger)
(require 'django-mode)
(require 'rails)
(require 'color-theme)
(setq viper-mode t)
(require 'viper)
(require 'vimpulse)
; js mode
(autoload 'js2-mode "js2" nil t)
(add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
(require 'anything-config)
